### ISSUE TITLE
What is LLN in experimental design?

### ISSUE THREAD

**Issue by Illustratien** [tillrose/BRIWECS_Data_Publication#21]
in data_cleaning.R line 66
`filter(Treatment != "LLN_WF",`
you remove the treatment "LLN_WF".

But it will also create the vacancy in experimental design ([figure/exp_deisgn.pdf](https://github.com/tillrose/BRIWECS_Data_Publication/blob/main/figure/exp_design.pdf)).
What is that and why should we remove it?

**Comment by tillrose** [comment]
In KAL 2018–2020 an additional treatment without nitrogen treatment was added to the experimental design. This management is excluded from the data set.
